package yunxun.ai.canary.backend.graph.service;

import org.springframework.stereotype.Service;
import yunxun.ai.canary.backend.graph.model.dto.ChartRequest;
import yunxun.ai.canary.backend.graph.model.dto.ChartResponse;

import java.util.Collections;
import java.util.List;
import java.util.Map;

/**
 * Core chart generation service.
 * <p>
 * In the current minimal version this service does not yet connect to
 * specific databases; it only echoes back a safe, well-structured
 * {@link ChartResponse} so that the MCP tool schema and frontend
 * integration can be validated first.
 * <p>
 * Later we can plug in real data sources (e.g. Neo4j, Mongo, MySQL)
 * and build engine-specific chart specifications here.
 */
@Service
public class GraphChartService {

    public ChartResponse generateChart(ChartRequest request) {
        String resolvedChartType = (request.getChartType() == null || request.getChartType().isBlank())
                ? "bar"
                : request.getChartType();

        String title = request.getQuestion() != null && !request.getQuestion().isBlank()
                ? request.getQuestion()
                : "Generated chart";

        // For now we don't connect to real data sources.
        // As a better demo than an empty chart, we synthesize a simple
        // monotonically increasing time-series when the question mentions
        // "近10年" so that the frontend can show a meaningful bar/line chart.
        List<String> xValues;
        List<Number> yValues;

        if (title.contains("近10年") || title.contains("近十年")) {
            xValues = List.of("2015", "2016", "2017", "2018", "2019",
                    "2020", "2021", "2022", "2023", "2024");
            yValues = List.of(150, 170, 190, 210, 230, 260, 290, 320, 350, 380);
        } else {
            xValues = List.of("A", "B", "C", "D");
            yValues = List.of(10, 20, 15, 30);
        }

        Map<String, Object> option = Map.of(
                "title", Map.of("text", title),
                "tooltip", Map.of("trigger", "axis"),
                "xAxis", Map.of("type", "category", "data", xValues),
                "yAxis", Map.of("type", "value"),
                "series", List.of(
                        Map.of(
                                "type", resolvedChartType.equals("line") ? "line" : "bar",
                                "data", yValues
                        )
                )
        );

        List<Map<String, Object>> dataRows = Collections.unmodifiableList(
                xValues.stream()
                        .map(x -> Map.<String, Object>of(
                                "x", x,
                                "value", yValues.get(xValues.indexOf(x))
                        ))
                        .toList()
        );

        return ChartResponse.builder()
                .chartType(resolvedChartType)
                .engine("echarts")
                .title(title)
                .description("Synthetic chart data generated by GraphChartService demo pipeline.")
                .chartSpec(option)
                .data(dataRows)
                .insightSummary("数值整体呈现上升趋势。")
                .insightBullets(List.of(
                        "横轴为类别或年份，纵轴为对应数值。",
                        "此数据为示例数据，用于演示图表生成与展示链路。"
                ))
                .build();
    }
}

